# AUC

In [9]:
import cv_datasets as md
import cv_models as mm
import cv_uncertainty as mu
import torch
from torch import nn
import scipy.stats as stats
import numpy as np
import pickle
import warnings

warnings.filterwarnings("ignore")
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt

with open("results/results_svhn.pkl", "rb") as f:
    r = pickle.load(f)

plt.rcParams["figure.figsize"] = [20, 4]
UNCER_QUANT = [
    mu.BLOODQuant().name + "_mean",
    mu.BLOODQuant().name + "_last",
    mu.LeastConfidentQuant().name,
    mu.EntropyQuant().name,
]
MODELS = ["ResNet34"]
NUM_SEEDS = 1


def variation(uncer, mode="_last"):
    if mode == "_last":
        return uncer[-1, :]
    elif mode == "_mean":
        return uncer.mean(axis=0)


for data_name, run in r.items():
    for model_name in MODELS:
        for uncer_name in UNCER_QUANT:
            BIO = False
            aucs = []
            for seed in range(NUM_SEEDS):
                if (
                    uncer_name.startswith(mu.BLOODQuant().name)
                    or uncer_name.startswith("repr_change")
                ) and not BIO:
                    BIO = True
                    mode = uncer_name[-5:]
                    uncer_name = uncer_name[:-5]
                elif not (
                    uncer_name.startswith(mu.BLOODQuant().name)
                    or uncer_name.startswith("repr_change")
                ):
                    mode = ""
                uncer_id = run[model_name]["fine-tuned"][seed][uncer_name]["id"]
                uncer_id = (
                    variation(uncer_id, mode=mode)
                    if uncer_name in ["BLOOD", "repr_change"]
                    else uncer_id
                )
                uncer_id = -uncer_id if uncer_name in ["repr_change", "least_confident"] else uncer_id
                uncer_ood = run[model_name]["fine-tuned"][seed][uncer_name]["ood"]
                uncer_ood = (
                    variation(uncer_ood, mode=mode)
                    if uncer_name in ["BLOOD", "repr_change"]
                    else uncer_ood
                )
                uncer_ood = -uncer_ood if uncer_name in ["repr_change", "least_confident"] else uncer_ood

                print(uncer_id)
                DATA = [0 for _ in range(len(uncer_id))] + [
                    1 for _ in range(len(uncer_ood))
                ]
                aucs.append(roc_auc_score(DATA, uncer_id.tolist() + uncer_ood.tolist()))
            aucs = np.array(aucs)
            print(
                f"{data_name} - {model_name} [{uncer_name+mode}]: AUC = {round(aucs.mean()*100, 2):.2f} $\pm$ {round(aucs.std()*100, 2):.2f}"
            )
        print()

tensor([34639.3750, 37134.4922, 39328.8359,  ..., 50734.3750, 34148.8906,
        43947.0234])
cifar10 - ResNet34 [BLOOD_mean]: AUC = 83.82 $\pm$ 0.00
tensor([1232.9268, 1300.3823, 1597.1713,  ..., 1094.7610, 1350.4053,
        1678.7405])
cifar10 - ResNet34 [BLOOD_last]: AUC = 14.32 $\pm$ 0.00
[-0.99046785 -0.99999964 -0.9998667  ... -0.9999951  -0.9999999
 -1.        ]
cifar10 - ResNet34 [least_confident]: AUC = 90.51 $\pm$ 0.00
[0.0540536  0.0001247  0.00142588 ... 0.00016044 0.00012446 0.00012434]
cifar10 - ResNet34 [entropy]: AUC = 91.55 $\pm$ 0.00

tensor([56833.1445, 43070.3242, 31927.2637,  ..., 38839.3633, 31749.0820,
        27377.2891])
cifar100 - ResNet34 [BLOOD_mean]: AUC = 86.40 $\pm$ 0.00
tensor([2170.4409, 2764.2944, 2381.1704,  ..., 2241.0688, 2340.4319,
        2138.9243])
cifar100 - ResNet34 [BLOOD_last]: AUC = 23.54 $\pm$ 0.00
[-0.8751067  -0.99965143 -0.9730391  ... -0.9999968  -0.9803402
 -0.9044189 ]
cifar100 - ResNet34 [least_confident]: AUC = 70.12 $\pm$ 0.00
[

In [7]:
import numpy as np
import pickle
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import roc_curve, roc_auc_score

with open('results/results_svhn.pkl', 'rb') as f: 
    r = pickle.load(f)
    
plt.rcParams["figure.figsize"] = [20, 4]
UNCER_QUANT = [mu.BLOODQuant().name+"_mean", mu.BLOODQuant().name+"_last", mu.LeastConfidentQuant().name, mu.EntropyQuant().name]
MODELS = ["ResNet34"] 
NUM_SEEDS = 5

def variation(uncer, mode="last"):
    if mode == "last":
        return uncer[-1,:]
    elif mode == "mean":
        return uncer.mean(axis=0)
    
for data_name, run in r.items():
    for model_name in MODELS:
        for uncer_name in UNCER_QUANT:
            for seed in range(NUM_SEEDS):               
                uncer_id = run[model_name]["fine-tuned"][seed][uncer_name]["id"]
                uncer_id = variation(uncer_id) if uncer_name in ["BLOOD", "repr_change"] else uncer_id
                uncer_id = -uncer_id if uncer_name == "repr_change" else uncer_id
                uncer_ood = run[model_name]["fine-tuned"][seed][uncer_name]["shifted"]
                uncer_ood = variation(uncer_ood) if uncer_name in ["BLOOD", "repr_change"] else uncer_ood
                uncer_ood = -uncer_ood if uncer_name == "repr_change" else uncer_ood
                
                DATA = [0 for _ in range(len(uncer_id))] + [1 for _ in range(len(uncer_ood))]
                fpr, tpr, _ = roc_curve(DATA, uncer_id.tolist()+uncer_ood.tolist())
                aucs.append(roc_auc_score(DATA, uncer_id.tolist()+uncer_ood.tolist()))
            aucs = np.array(aucs)
            print(f"{data_name} - {model_name} [{uncer_name}]: AUC = {round(aucs.mean()*100, 2):.2f} $\pm$ {round(aucs.std()*100, 2):.2f}")
        print()

KeyError: 'shifted'

# AUPR

In [ ]:
import my_datasets as md
import my_models as mm
import my_uncertainty as mu
import torch
from torch import nn
import scipy.stats as stats
import numpy as np
import pickle
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import auc, precision_recall_curve

with open('results.pkl', 'rb') as f: 
    r = pickle.load(f)
    
plt.rcParams["figure.figsize"] = [20, 4]
UNCER_QUANT = [mu.BLOODQuant().name+"_mean", mu.BLOODQuant().name+"_last", mu.LeastConfidentQuant().name, mu.EntropyQuant().name, mu.MCDropoutQuant().name, mu.GradQuant().name, mu.EnsambleQuant().name, mu.TemperatureScalingQuant().name, mu.MahalanobisQuant().name]
MODELS = ["ELECTRA"] 
NUM_SEEDS = 5

def variation(uncer, mode="_last"):
    if mode == "_last":
        return uncer[-1,:]
    elif mode == "_mean":
        return uncer.mean(axis=0)
    
for data_name, run in r.items():
    for model_name in MODELS:
        for uncer_name in UNCER_QUANT:
            BIO = False
            fig, axs = plt.subplots(1, NUM_SEEDS)
            if NUM_SEEDS == 1:
                axs = [axs]
            aucs = []
            for seed in range(NUM_SEEDS):
                uncer_id = run[model_name]["fine-tuned"][seed][uncer_name]["id"]
                uncer_id = variation(uncer_id, mode=mode) if uncer_name in ["BLOOD", "repr_change"] else uncer_id
                uncer_id = -uncer_id if uncer_name == "repr_change" else uncer_id
                uncer_ood = run[model_name]["fine-tuned"][seed][uncer_name]["ood"]
                uncer_ood = variation(uncer_ood, mode=mode) if uncer_name in ["BLOOD", "repr_change"] else uncer_ood
                uncer_ood = -uncer_ood if uncer_name == "repr_change" else uncer_ood
                DATA = [1 for _ in range(len(uncer_id))] + [0 for _ in range(len(uncer_ood))]
                uncer_id = -uncer_id
                uncer_ood = -uncer_ood
                precision, recall, _ = precision_recall_curve(DATA, uncer_id.tolist()+uncer_ood.tolist())
                aucs.append(auc(recall, precision))
            aucs = np.array(aucs)
            print(f"{data_name} - {model_name} [{uncer_name+mode}]: AUPR = {round(aucs.mean()*100, 2):.2f} $\pm$ {round(aucs.std()*100, 2):.2f}")
        print()

In [ ]:
import my_datasets as md
import my_models as mm
import my_uncertainty as mu
import torch
from torch import nn
import scipy.stats as stats
import numpy as np
import pickle
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import roc_curve, roc_auc_score

with open('results-shifted-sst.pkl', 'rb') as f: 
    r = pickle.load(f)
    
plt.rcParams["figure.figsize"] = [20, 4]
UNCER_QUANT = [mu.BLOODQuant().name+"_mean", mu.BLOODQuant().name+"_last", mu.LeastConfidentQuant().name, mu.EntropyQuant().name, mu.MCDropoutQuant().name, mu.GradQuant().name, mu.EnsambleQuant().name, mu.TemperatureScalingQuant().name, mu.MahalanobisQuant().name]
MODELS = ["RoBERTa", "ELECTRA"]
NUM_SEEDS = 5

def variation(uncer, mode="last"):
    if mode == "last":
        return uncer[-1,:]
    elif mode == "mean":
        return uncer.mean(axis=0)
    
for data_name, run in r.items():
    for model_name in MODELS:
        for uncer_name in UNCER_QUANT:
            if NUM_SEEDS == 1:
                axs = [axs]
            aucs = []
            for seed in range(NUM_SEEDS):               
                uncer_id = run[model_name]["fine-tuned"][seed][uncer_name]["id"]
                uncer_id = variation(uncer_id) if uncer_name in ["BLOOD", "repr_change"] else uncer_id
                uncer_id = -uncer_id if uncer_name == "repr_change" else uncer_id
                uncer_ood = run[model_name]["fine-tuned"][seed][uncer_name]["shifted"]
                uncer_ood = variation(uncer_ood) if uncer_name in ["BLOOD", "repr_change"] else uncer_ood
                uncer_ood = -uncer_ood if uncer_name = "repr_change" else uncer_ood
                
                DATA = [1 for _ in range(len(uncer_id))] + [0 for _ in range(len(uncer_ood))]
                uncer_id = -uncer_id
                uncer_ood = -uncer_ood
                precision, recall, _ = precision_recall_curve(DATA, uncer_id.tolist()+uncer_ood.tolist())
                aucs.append(auc(recall, precision))
            aucs = np.array(aucs)
            print(f"{data_name} - {model_name} [{uncer_name}]: AUPR = {round(aucs.mean()*100, 2):.2f} $\pm$ {round(aucs.std()*100, 2):.2f}")
        print()

# FPR@95TPR

In [5]:
import numpy as np
import torch

def fpr95(uncers_id, uncers_ood):
    th = np.percentile(uncers_id, 95)
    if torch.is_tensor(uncers_ood):
        uncers_ood = uncers_ood.cpu().detach().numpy()
    return (uncers_ood < th).mean()

In [ ]:
import my_datasets as md
import my_models as mm
import my_uncertainty as mu
import torch
from torch import nn
import scipy.stats as stats
import numpy as np
import pickle
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import roc_curve, roc_auc_score, auc, precision_recall_curve

with open('results.pkl', 'rb') as f: 
    r = pickle.load(f)
    
plt.rcParams["figure.figsize"] = [20, 4]
UNCER_QUANT = [mu.BLOODQuant().name+"_mean", mu.BLOODQuant().name+"_last", mu.LeastConfidentQuant().name, mu.EntropyQuant().name, mu.MCDropoutQuant().name, mu.GradQuant().name, mu.EnsambleQuant().name, mu.TemperatureScalingQuant().name, mu.MahalanobisQuant().name]
MODELS = ["ELECTRA"] 
NUM_SEEDS = 5

def variation(uncer, mode="_last"):
    if mode == "_last":
        return uncer[-1,:]
    elif mode == "_mean":
        return uncer.mean(axis=0)
    
for data_name, run in r.items():
    for model_name in MODELS:
        for uncer_name in UNCER_QUANT:
            BIO = False
            fig, axs = plt.subplots(1, NUM_SEEDS)
            if NUM_SEEDS == 1:
                axs = [axs]
            aucs = []
            for seed in range(NUM_SEEDS):
                uncer_id = run[model_name]["fine-tuned"][seed][uncer_name]["id"]
                uncer_id = variation(uncer_id, mode=mode) if uncer_name in ["BLOOD", "repr_change"] else uncer_id
                uncer_id = -uncer_id if uncer_name == "repr_change" else uncer_id
                uncer_ood = run[model_name]["fine-tuned"][seed][uncer_name]["ood"]
                uncer_ood = variation(uncer_ood, mode=mode) if uncer_name in ["BLOOD", "repr_change"] else uncer_ood
                uncer_ood = -uncer_ood if uncer_name == "repr_change" else uncer_ood
                aucs.append(fpr95(uncer_id, uncer_ood))
            aucs = np.array(aucs)
            print(f"{data_name} - {model_name} [{uncer_name+mode}]: FPR = {round(aucs.mean()*100, 2):.2f} $\pm$ {round(aucs.std()*100, 2):.2f}")
        print()

In [ ]:
import my_datasets as md
import my_models as mm
import my_uncertainty as mu
import torch
from torch import nn
import matplotlib.pyplot as plt
import scipy.stats as stats
import numpy as np
import pickle
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import roc_curve, roc_auc_score

with open('results-shifted-sst.pkl', 'rb') as f: 
    r = pickle.load(f)
    
plt.rcParams["figure.figsize"] = [20, 4]
UNCER_QUANT = [mu.BLOODQuant().name+"_mean", mu.BLOODQuant().name+"_last", mu.BLOODQuant().name, mu.EntropyQuant().name, mu.MCDropoutQuant().name, mu.GradQuant().name, mu.EnsambleQuant().name, mu.TemperatureScalingQuant().name, mu.MahalanobisQuant().name]
MODELS = ["RoBERTa", "ELECTRA"]
NUM_SEEDS = 5

def variation(uncer, mode="last"):
    if mode == "last":
        return uncer[-1,:]
    elif mode == "mean":
        return uncer.mean(axis=0)
    
for data_name, run in r.items():
    for model_name in MODELS:
        for uncer_name in UNCER_QUANT:
            if NUM_SEEDS == 1:
                axs = [axs]
            aucs = []
            for seed in range(NUM_SEEDS):               
                uncer_id = run[model_name]["fine-tuned"][seed][uncer_name]["id"]
                uncer_id = variation(uncer_id) if uncer_name in ["BLOOD", "repr_change"] else uncer_id
                uncer_id = -uncer_id if uncer_name == "repr_change" else uncer_id
                uncer_ood = run[model_name]["fine-tuned"][seed][uncer_name]["shifted"]
                uncer_ood = variation(uncer_ood) if uncer_name in ["BLOOD", "repr_change"] else uncer_ood
                uncer_ood = -uncer_ood if uncer_name == "repr_change" else uncer_ood
                
                aucs.append(fpr95(uncer_id, uncer_ood))
                
            aucs = np.array(aucs)
            print(f"{data_name} - {model_name} [{uncer_name}]: AUPR = {round(aucs.mean()*100, 2):.2f} $\pm$ {round(aucs.std()*100, 2):.2f}")